info:
  app:
    parentGroupId: @project.parent.groupId@
    groupId: @project.groupId@
    artifactId: @project.artifactId@
    version: @project.version@
server:
  port: 9999
spring:
  thymeleaf:
    cache: false
  application:
    name: logging-previewer